# -*- coding: utf-8 -*-
"""BondPrice_File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1at3xSp-BoX7bYkHwpktrwBHiBgBKKpie
"""

import numpy as np

def getBondPrice(y, face, couponRate, m, ppy=1):
    t = np.arange(1, m * ppy + 1)  # Time periods
    discount_factors = (1 + y / ppy) ** -t  # Present value factors
    sum_pv = discount_factors.sum()  # Sum of present value factors
    pv_at_maturity = discount_factors[-1]  # Present value at maturity
    bond_price = ((sum_pv * couponRate) + pv_at_maturity) * face
    return bond_price

# Test values
y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy = 1  # Payment per year set to 1

# Compute bond price
bond_price = getBondPrice(y, face, couponRate, m, ppy)
print(f"{bond_price:,.0f}")

import numpy as np

def getBondPrice(y, face, couponRate, m, ppy=2):
    p = np.arange(1, m * ppy + 1)  # Time periods
    discount_factors = (1 + y / ppy) ** -p  # Present value factors
    sum_pv = discount_factors.sum()  # Sum of present value factors
    pv_at_maturity = discount_factors[-1]  # Present value at maturity
    bond_price = ((sum_pv * (couponRate / ppy)) + pv_at_maturity) * face
    return bond_price

# Test values
y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy = 2  # Payment per year set to 2

# Compute bond price
bond_price = getBondPrice(y, face, couponRate, m, ppy)
print(f"{bond_price:,.0f}")