# -*- coding: utf-8 -*-
"""WhoAmI_File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fwgd6QYXw1BqGMKbzhUIjoOU257cjzg
"""

# Identify yourself for grading

def WhoAmI():
  return('xh2662')